/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentbank;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class StudentBank {
    public static void main(String[] args) {
        SpringApplication.run(StudentBank.class, args);
    }
}

