server:
  port: 8080

spring:
  datasource:
    username: root
    password: "@Riat-pass!234"
    url: jdbc:mysql://localhost:3306/studentBank
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true